### ISSUE TITLE
Share with the OpenSeadragon community?

### ISSUE THREAD

**Issue by iangilman** [IMAmuseum/tile_generator#1]
It looks like this just builds DZI-compatible titles but doesn't write the DZI file, is that right? Any plans to add that extra feature?

**Comment by iangilman** [comment]
For context, I'm referring to adding a link to this project from:

http://openseadragon.github.io/examples/creating-zooming-images/

@jeremytubbs knows what I'm talking about…

**Comment by jeremytubbs** [comment]
Sorry, this is not the tiler we are using in production fo python... we are using: https://github.com/openzoom/deepzoom.py

**Comment by iangilman** [comment]
Gotcha...I was confused by this comment: 

https://news.ycombinator.com/item?id=10229083

Btw, we've added the IMA collection to OSD's "in the wild" page: 

http://openseadragon.github.io/examples/in-the-wild/

**Comment by jeremytubbs** [comment]
Thanks! ... It was my mistake. I thought we had rolled our own python code for the tiles generation and thought that was the correct repo to point you towards.

**Comment by iangilman** [comment]
Cool. I'm actually glad to hear that deepzoom.py is working out well. :-)
